modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="kaleidoscope_snack"
version="0.1.2"
displayName="\u68EE\u7F57\u7269\u8BED\uFF1A\u5C0F\u5403"
displayURL="https://github.com/com-in/Kaleidoscope-Snack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Ctoy"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.kaleidoscope_snack]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.232,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.kaleidoscope_snack]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.kaleidoscope_snack]]
    modId="kaleidoscope_cookery"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration